package main.projetobd;

import control.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import javafx.scene.input.KeyCode;
import javax.swing.JOptionPane;

/**
 *
 * @author Ariel Reis
 */
public class TelaLogin extends javax.swing.JFrame{
    
    public static MySQLConnection conexaoPrincipal;
    public static String nomeDoUsuario = null;
    private int typeUser = 0;

    protected String tipoDeUsuarioString(){
        String usuarioTipo;
        switch(typeUser){
            case 1:
                usuarioTipo = "Administrador";
                break;
            case 2:
                usuarioTipo = "Gerente";
                break;
            case 3:
                usuarioTipo = "Funcionário";
                break;
            case 4:
                usuarioTipo = "Contador";
                break;
            default:
                usuarioTipo = "Usuário não autenticado";
        }
        return usuarioTipo;
    }
    
    private boolean usuarioTemTipo(){
        return !(typeUser == 0 || typeUser > 4);
    }
    
    private boolean validaUsuario(){
       String username = txtUsername.getText().toLowerCase();
       int password = 0;
       try{
           password = Integer.parseInt(txtUserPassword.getText());
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Sua senha deve conter apenas números.", "Erro ao validar!", JOptionPane.ERROR_MESSAGE);
       }
       QEncrypt encrypter = new QEncrypt(String.valueOf(password));
       String bigSelect = "SELECT func_login, func_pw, func_nome, func_tipo FROM academia.ade_funcionario WHERE func_login = '" + username + "' AND func_pw = '" + encrypter.getEncrypted() + "';";
       boolean validado = false;
       try{
           
           ResultSet rs = conexaoPrincipal.abrirConsulta(bigSelect);
           
           Tabela tabela = new Tabela();
           String[][] tabelaFullData = tabela.getAllDataFromTable(rs);
           nomeDoUsuario = tabelaFullData[0][2];
           typeUser = Integer.parseInt(tabelaFullData[0][3]);
           if(tabelaFullData != null){
               System.out.println("\n\n##############################");
               System.out.println("User: " + nomeDoUsuario);
               System.out.println("Message: Logado com sucesso");
               JOptionPane.showMessageDialog(null, "Seja bem vindo ao sistema, " + nomeDoUsuario +"!", "Logado com sucesso", JOptionPane.PLAIN_MESSAGE);
               validado = true;
           }else{               
               System.out.println("\n\n##############################");
               System.out.println("User: " + nomeDoUsuario);
               System.out.println("Message: Não autenticado");
               JOptionPane.showMessageDialog(null, "Usuário não autenticado.", "Erro ao autenticar", JOptionPane.ERROR_MESSAGE);
           }
         
       }catch(Exception e){
               System.out.println("\n\n##############################");
               System.out.println("User: " + nomeDoUsuario);
               System.out.println("Message: Não autenticado");
               System.out.println("Erro:" + ExceptionTratador.exceptionToString(e.toString()));
               JOptionPane.showMessageDialog(null, "Usuário não autenticado.", "Erro ao autenticar", JOptionPane.ERROR_MESSAGE);
       }
       return validado;
    }
    
    /**
     * @author Ariel Reis
     * @since 2017-03-10
     */
    public TelaLogin() {
        conexaoPrincipal = new MySQLConnection("localhost", "3306", "root", "1234", "academia");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - AcaDEmia");
        setResizable(false);

        txtUserPassword.setToolTipText("");
        txtUserPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserPasswordKeyPressed(evt);
            }
        });

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha:");

        jButton1.setText("Logar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername)
                    .addComponent(txtUserPassword)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        if(validaUsuario()){
           TelaDashboard dashBoard = new TelaDashboard();
           dashBoard.setVisible(true);
           this.dispose();
        }else{
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUserPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserPasswordKeyPressed
        
        if(evt.getKeyCode() == 10){
             if(validaUsuario()){
                TelaDashboard dashBoard = new TelaDashboard();
                dashBoard.setVisible(true);
                this.dispose();
             }else{
              
             }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtUserPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
